name: "CI: Build"

on: [push, pull_request]

jobs:
  build:
    name: "Build"
    runs-on: ubuntu-latest
    container:
      image: bilelmoussaoui/flatpak-github-actions:gnome-nightly
    steps:
    - uses: actions/checkout@v1
    - name: Install Dependencies
      run: |
        apt update
        apt install -y meson ninja cmake appstream-util libadwaita-1-dev libgtk-4-dev libgstreamer1.0-dev libgee-0.8-dev libsoup-3.0-dev libjson-glib-dev valac
    - name: Build
      env:
        DESTDIR: out
      run: |
        meson setup builddir
        ninja -C build install