<<<<<<< HEAD
<<<<<<< HEAD
name: CI Light
=======
name: CI
>>>>>>> 1685256 (Изменить файлы workflow)
=======
name: CI Light
>>>>>>> c45a078 (Изменить имя у workflow)

on:
  push:
    branches:
      - 'master'  # Запускать workflow только для веток разработки
<<<<<<< HEAD
<<<<<<< HEAD
  pull_request:
=======
>>>>>>> 1685256 (Изменить файлы workflow)
=======
  pull_request:
>>>>>>> 304603d (Обновить CI)

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest

    container:
      image: valalang/lint

    steps:
    - uses: actions/checkout@v4
    - name: Lint
      run: io.elementary.vala-lint -d .

  test-build:
    name: Build
    runs-on: ubuntu-latest
    needs: lint

    container:
      image: bilelmoussaoui/flatpak-github-actions:gnome-nightly
      options: --privileged

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Run tests and lint
      uses: flatpak/flatpak-github-actions/flatpak-builder@v6
      with:
        bundle: cassette.flatpak
        manifest-path: build-aux/flatpak/io.github.Rirusha.Cassette.Devel.json
        run-tests: true
        cache-key: flatpak-builder-${{ github.sha }} 