name: CI Pull Request

on:
  pull_request:

permissions:
  contents: read

jobs:
  lint:
    name: Lint Check
    runs-on: ubuntu-latest

    container:
      image: valalang/lint

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Lint Vala
        run: io.elementary.vala-lint -d . -c vala-lint.conf

      - name: Install blueprint-compiler Blueptint
        run: sudo apt install blueprint-compiler
        
      - name: Lint Blueprint
        run: blueprint-compiler format -s 2 data/ui/*.blp

  test-build:
    name: Test Build
    runs-on: ubuntu-latest
    needs: lint

    container:
      image: bilelmoussaoui/flatpak-github-actions:gnome-46
      options: --privileged

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Run tests and lint
      uses: flatpak/flatpak-github-actions/flatpak-builder@v6
      with:
        bundle: cassette.flatpak
        manifest-path: build-aux/flatpak/io.github.Rirusha.Cassette-Devel.json
        run-tests: true
        cache-key: flatpak-builder-${{ github.sha }} 