name: CI Pull Request

on:
  pull_request:

permissions:
  contents: read

jobs:
  lint-vala:
    name: Lint vala files
    runs-on: ubuntu-latest

    container:
      image: valalang/lint

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Lint Vala
        run: io.elementary.vala-lint -d . -c vala-lint.conf

  lint-blp:
    name: Lint blueprint ui files
    runs-on: ubuntu-latest
    needs: lint-vala

    container:
      image: bilelmoussaoui/flatpak-github-actions:gnome-46

    steps:
      - name: Clone blueprint repo
        run: git clone https://gitlab.gnome.org/hub/blueprint-compiler.git && cd blueprint-compiler

      - name: Build blueprin-compiler
        run: meson setup builddir

      - name: Install blueprint-compiler
        run: ninja -C builddir install

      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Lint Blueprint
        run: blueprint-compiler format -s 2 data/ui/*.blp

  test-build:
    name: Test Build
    runs-on: ubuntu-latest
    needs: lint-blp

    container:
      image: bilelmoussaoui/flatpak-github-actions:gnome-46
      options: --privileged

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Run tests and lint
      uses: flatpak/flatpak-github-actions/flatpak-builder@v6
      with:
        bundle: cassette.flatpak
        manifest-path: build-aux/flatpak/io.github.Rirusha.Cassette-Devel.json
        run-tests: true
        cache-key: flatpak-builder-${{ github.sha }} 