name: Deploy

on:
  schedule:
    - cron: 0 0 * * *
  workflow_dispatch:

jobs:
  pr-deploy:
    name: Pull Request to deploy branch
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Config git
        run: |
          git config --global user.name "auto-deployer"
          git config --global user.email "rirusha@noreply.github.com"

      - name: Checkout branch
        run: git checkout ${{ env.DEVEL_SLICE_BRANCH_NAME }}
      
      - name: Merge changes
        run: |
          git merge origin/dev-* --no-edit
          git push origin ${{ env.DEVEL_SLICE_BRANCH_NAME }}

  build:
    name: Build
    runs-on: ubuntu-latest
    container:
      image: bilelmoussaoui/flatpak-github-actions:gnome-nigthly
      options: --priveleged
    
    strategy:
      matrix:
        arch: [x86_64, aarch64]
      fail-fast: false
      max-parallel: 1
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup QEMU
        id: qemu
        uses: docker/setup-qemu-action@v3
        with:
          platforms: arm64

      - name: Setup GPG
        id: gpg
        uses: crazy-max/ghaction-import-gpg@v6
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.GPG_PASSPHRASE }}
        
      - name: Build and install deps
        uses: flatpak/flatpak-github-actions/flatpak-builder@v6
        with:
          bundle: ${{ env.DEVEL_APP_ID }}.flatpak
          manifest-path: build-aux/flatpak/${{ env.DEVEL_APP_ID }}.json
          repository-url: ${{ env.REPO_URL }}
          repository-name: ${{ env.REPO_BANE }}
          # run-tests: true
          gpg-sign: ${{ steps.gpg.outputs.fingerprint }}
          cache-key: flatpak-builder-${{ github.sha }}

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: build
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
