name: Deploy

on:
  schedule:
    - cron: 0 0 * * *
  workflow_dispatch:

jobs:
  sync-branches:
    name: Rebase devel-slice on dev-*
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Config git
        run: |
          git config --global user.name "robot-debil"
          git config --global user.email "rirusha@noreply.github.com"

      - name: Checkout all
        run: |
          remote_branches=$(git branch -r | grep -v '\->' | awk -F'/' '{print $2}')
          for branch in $remote_branches; do git checkout -B $branch origin/$branch; done
          git checkout devel-slice

      - name: Rebase & Push
        # Должна существовать только одна ветка dev-*
        run: |        
          git branch --list | grep "dev-" | while read -r branch; do git rebase --reapply-cherry-picks --strategy=ours "$branch"; done
    
      - name: Push
        run: |        
          git push --force origin devel-slice
      

  flatter:
    name: Flatter
    runs-on: ubuntu-latest
    needs: sync-branches

    container:
      image: ghcr.io/andyholmes/flatter/gnome:master
      options: --privileged

    strategy:
      matrix:
        arch: [x86_64, aarch64]
      fail-fast: false
      max-parallel: 1

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: devel-slice

      - name: Setup QEMU
        if: ${{ matrix.arch == 'aarch64' }}
        id: qemu
        uses: docker/setup-qemu-action@v3
        with:
          platforms: arm64

      - name: Setup GPG
        id: gpg
        uses: crazy-max/ghaction-import-gpg@v6
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.GPG_PASSPHRASE }}

      - name: Build 
        uses: andyholmes/flatter@main
        with:
          files: |
            build-aux/flatpak/io.github.Rirusha.Cassette-Devel.json
          arch: ${{ matrix.arch }}
          gpg-sign: ${{ steps.gpg.outputs.fingerprint }}
          upload-bundles: true
          upload-pages-artifact: ${{ matrix.arch == 'aarch64' }}

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: flatter
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4