name: "Lint, Build, Deploy"

on:  
  push:
    branches:
      - 'dev-*'  # Запускать workflow только для веток разработки

jobs:
  lint:
    name: "Lint"
    runs-on: ubuntu-latest

    container:
      image: valalang/lint

    steps:
    - uses: actions/checkout@v1
    - name: Lint
      run: io.elementary.vala-lint -d .

  build:
    name: "Build"
    runs-on: ubuntu-latest

    container:
      image: bilelmoussaoui/flatpak-github-actions:gnome-nightly
      options: --privileged

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Run tests and lint
      uses: flatpak/flatpak-github-actions/flatpak-builder@v6
      with:
        bundle: cassette.flatpak
        manifest-path: build-aux/flatpak/io.github.Rirusha.Cassette.Devel.json
        # run-tests: true
        cache-key: flatpak-builder-${{ github.sha }}

    - name: Commit to deploy branch
      if: success()
      uses: stefanzweifel/git-auto-commit-action@v5
      with:
        branch: deploy
        commit_options: '--no-verify --signoff'
        