name: PR

on:
  schedule:
    - cron: 0 0 * * *
  workflow_dispatch:

jobs:
  create-pr:
    name: Create PR
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: devel-slice

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          base: dev-0.2
          branch: devel-slice